import { MigrationInterface, QueryRunner } from "typeorm";

export class UuidAndAutoMappedRelationsRefactor1773268933164 implements MigrationInterface {
    name = 'UuidAndAutoMappedRelationsRefactor1773268933164'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "provider_user_info" DROP CONSTRAINT "FK_c5708135f38e549be0deea94891"`);
        await queryRunner.query(`ALTER TABLE "serving_areas" DROP CONSTRAINT "FK_ccdcd71ebbe5e41b46c24a2d3cf"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_ce21261bfdd3e1aee0ff847fc71"`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" DROP CONSTRAINT "FK_873d512873c9ac9753916929b4d"`);
        await queryRunner.query(`ALTER TABLE "provider_payments" DROP CONSTRAINT "FK_05dad2afcf8479855da1282264e"`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" DROP CONSTRAINT "FK_eebde20dc0ea854cd3632ece39e"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP CONSTRAINT "FK_6b5553e80209c66531c8cfc79b7"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP CONSTRAINT "FK_6381d467e80a5b4c2e7fb7984df"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_da8207850c9b5e214a5e7822cc6"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_2ac580d173f4738143cf874a3b3"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_14b384c3f2cba645a89c0c70f4a"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_96071d5ba65f9c64f0f2dfdfaf3"`);
        await queryRunner.query(`ALTER TABLE "serving_areas" RENAME COLUMN "branchId" TO "branch_id"`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" DROP CONSTRAINT "REL_c5708135f38e549be0deea9489"`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" DROP COLUMN "providerProfileId"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "providerProfileId"`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" DROP CONSTRAINT "REL_873d512873c9ac9753916929b4"`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" DROP COLUMN "providerProfileId"`);
        await queryRunner.query(`ALTER TABLE "provider_payments" DROP CONSTRAINT "REL_05dad2afcf8479855da1282264"`);
        await queryRunner.query(`ALTER TABLE "provider_payments" DROP COLUMN "providerProfileId"`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" DROP COLUMN "planId"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP CONSTRAINT "REL_6b5553e80209c66531c8cfc79b"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP COLUMN "providerProfileId"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP COLUMN "billingCycleId"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "statusId"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "providerTypeId"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "companyTypeId"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD "billing_cycle_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "status_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" ADD CONSTRAINT "UQ_ce9ee8785f564b8c5e2636d658e" UNIQUE ("provider_profile_id")`);
        await queryRunner.query(`ALTER TABLE "serving_areas" ALTER COLUMN "branch_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" ADD CONSTRAINT "UQ_e0156372eaf3d0b922418702939" UNIQUE ("provider_profile_id")`);
        await queryRunner.query(`ALTER TABLE "provider_payments" ADD CONSTRAINT "UQ_e2eb5d82f6a2f941858c2fc348c" UNIQUE ("provider_profile_id")`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" DROP CONSTRAINT "UQ_6618a0c895ca7a53bc02a592b60"`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" DROP COLUMN "plan_id"`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" ADD "plan_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD CONSTRAINT "UQ_d31b274fa7b95969da8a8b43eb6" UNIQUE ("provider_profile_id")`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP COLUMN "selected_plan_id"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD "selected_plan_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "provider_type_id"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "provider_type_id" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "company_type_id"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "company_type_id" uuid`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" ADD CONSTRAINT "UQ_6618a0c895ca7a53bc02a592b60" UNIQUE ("plan_id", "feature_text")`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" ADD CONSTRAINT "FK_ce9ee8785f564b8c5e2636d658e" FOREIGN KEY ("provider_profile_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "serving_areas" ADD CONSTRAINT "FK_64a7491a2aa6ccad424658dd925" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_0f0d4fb3d355481de8d2aabe5e3" FOREIGN KEY ("provider_profile_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" ADD CONSTRAINT "FK_e0156372eaf3d0b922418702939" FOREIGN KEY ("provider_profile_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_payments" ADD CONSTRAINT "FK_e2eb5d82f6a2f941858c2fc348c" FOREIGN KEY ("provider_profile_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" ADD CONSTRAINT "FK_6b01b9cbcc3119dac45d59f1848" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD CONSTRAINT "FK_d31b274fa7b95969da8a8b43eb6" FOREIGN KEY ("provider_profile_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD CONSTRAINT "FK_c8b3abdcbe1366928f333a39ca9" FOREIGN KEY ("selected_plan_id") REFERENCES "subscription_plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD CONSTRAINT "FK_bb7ac5533ea8aefbfdd4a4d28b6" FOREIGN KEY ("billing_cycle_id") REFERENCES "lookup_billing_cycle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_c81d186988c9ce0665cba04bae4" FOREIGN KEY ("status_id") REFERENCES "lookup_profile_status"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_c91b4eddecde820d748b3af5e85" FOREIGN KEY ("provider_type_id") REFERENCES "lookup_provider_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_404e70dd4672fb13266def02515" FOREIGN KEY ("company_type_id") REFERENCES "lookup_company_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_404e70dd4672fb13266def02515"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_c91b4eddecde820d748b3af5e85"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_c81d186988c9ce0665cba04bae4"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP CONSTRAINT "FK_bb7ac5533ea8aefbfdd4a4d28b6"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP CONSTRAINT "FK_c8b3abdcbe1366928f333a39ca9"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP CONSTRAINT "FK_d31b274fa7b95969da8a8b43eb6"`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" DROP CONSTRAINT "FK_6b01b9cbcc3119dac45d59f1848"`);
        await queryRunner.query(`ALTER TABLE "provider_payments" DROP CONSTRAINT "FK_e2eb5d82f6a2f941858c2fc348c"`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" DROP CONSTRAINT "FK_e0156372eaf3d0b922418702939"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_0f0d4fb3d355481de8d2aabe5e3"`);
        await queryRunner.query(`ALTER TABLE "serving_areas" DROP CONSTRAINT "FK_64a7491a2aa6ccad424658dd925"`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" DROP CONSTRAINT "FK_ce9ee8785f564b8c5e2636d658e"`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" DROP CONSTRAINT "UQ_6618a0c895ca7a53bc02a592b60"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "company_type_id"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "company_type_id" character varying`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "provider_type_id"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "provider_type_id" character varying`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP COLUMN "selected_plan_id"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD "selected_plan_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP CONSTRAINT "UQ_d31b274fa7b95969da8a8b43eb6"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" DROP COLUMN "plan_id"`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" ADD "plan_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" ADD CONSTRAINT "UQ_6618a0c895ca7a53bc02a592b60" UNIQUE ("feature_text", "plan_id")`);
        await queryRunner.query(`ALTER TABLE "provider_payments" DROP CONSTRAINT "UQ_e2eb5d82f6a2f941858c2fc348c"`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" DROP CONSTRAINT "UQ_e0156372eaf3d0b922418702939"`);
        await queryRunner.query(`ALTER TABLE "serving_areas" ALTER COLUMN "branch_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" DROP CONSTRAINT "UQ_ce9ee8785f564b8c5e2636d658e"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "status_id"`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" DROP COLUMN "billing_cycle_id"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "companyTypeId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "providerTypeId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "statusId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD "billingCycleId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD "providerProfileId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD CONSTRAINT "REL_6b5553e80209c66531c8cfc79b" UNIQUE ("providerProfileId")`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" ADD "planId" character varying`);
        await queryRunner.query(`ALTER TABLE "provider_payments" ADD "providerProfileId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_payments" ADD CONSTRAINT "REL_05dad2afcf8479855da1282264" UNIQUE ("providerProfileId")`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" ADD "providerProfileId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" ADD CONSTRAINT "REL_873d512873c9ac9753916929b4" UNIQUE ("providerProfileId")`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "providerProfileId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" ADD "providerProfileId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" ADD CONSTRAINT "REL_c5708135f38e549be0deea9489" UNIQUE ("providerProfileId")`);
        await queryRunner.query(`ALTER TABLE "serving_areas" RENAME COLUMN "branch_id" TO "branchId"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_96071d5ba65f9c64f0f2dfdfaf3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_14b384c3f2cba645a89c0c70f4a" FOREIGN KEY ("companyTypeId") REFERENCES "lookup_company_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_2ac580d173f4738143cf874a3b3" FOREIGN KEY ("providerTypeId") REFERENCES "lookup_provider_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_da8207850c9b5e214a5e7822cc6" FOREIGN KEY ("statusId") REFERENCES "lookup_profile_status"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD CONSTRAINT "FK_6381d467e80a5b4c2e7fb7984df" FOREIGN KEY ("billingCycleId") REFERENCES "lookup_billing_cycle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_subscriptions" ADD CONSTRAINT "FK_6b5553e80209c66531c8cfc79b7" FOREIGN KEY ("providerProfileId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_plan_features" ADD CONSTRAINT "FK_eebde20dc0ea854cd3632ece39e" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_payments" ADD CONSTRAINT "FK_05dad2afcf8479855da1282264e" FOREIGN KEY ("providerProfileId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_compliance" ADD CONSTRAINT "FK_873d512873c9ac9753916929b4d" FOREIGN KEY ("providerProfileId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_ce21261bfdd3e1aee0ff847fc71" FOREIGN KEY ("providerProfileId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "serving_areas" ADD CONSTRAINT "FK_ccdcd71ebbe5e41b46c24a2d3cf" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_user_info" ADD CONSTRAINT "FK_c5708135f38e549be0deea94891" FOREIGN KEY ("providerProfileId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
