import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1782669467766 implements MigrationInterface {
    name = 'Migration1782669467766'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" DROP CONSTRAINT "FK_c18c6384104a029f1b34121e0e2"`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" DROP CONSTRAINT "FK_cadeafa1e4d4a8e7263d7a0f7d0"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_blogs_author"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP CONSTRAINT "FK_d4e2f8e131609f51df1182ffc59"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_ee11a5e8d47cd5e01747d52f3b3"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_032c8d929b0d60944f52d444e09"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_d732a878487323978f118ab361c"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_dec6205e2cd13841763710f9892"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_c113b7d5e19895123ebffb883df"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_ba7ceb19946b8b23bf5939c930f"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_d4e7e923e6bb78a8f0add754493"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_6b129b5f4433000c7f97399bfe9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_blogs_status"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP CONSTRAINT "UQ_4c1ab15e915d32b19ff924459fb"`);
        await queryRunner.query(`CREATE TYPE "public"."worker_profiles_status_enum" AS ENUM('AVAILABLE', 'BUSY', 'OFFLINE')`);
        await queryRunner.query(`CREATE TABLE "worker_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying, "status" "public"."worker_profiles_status_enum" NOT NULL DEFAULT 'AVAILABLE', "image_url" character varying, "user_id" uuid, "employer_provider_id" uuid, CONSTRAINT "REL_7c611bb4a08be1f32a858acc11" UNIQUE ("user_id"), CONSTRAINT "PK_400f6f30c94f164ebfc054c8c61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."worker_invitations_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "worker_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "email_or_phone" character varying NOT NULL, "name" character varying NOT NULL, "token" character varying NOT NULL, "status" "public"."worker_invitations_status_enum" NOT NULL DEFAULT 'PENDING', "expires_at" TIMESTAMP NOT NULL, "provider_id" uuid NOT NULL, CONSTRAINT "UQ_0dbf58d2edd2f890b83860db62f" UNIQUE ("token"), CONSTRAINT "PK_1b949cb59e40d6f3af0021dfcc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contracts_status_enum" AS ENUM('ACTIVE', 'IN_PROGRESS', 'PROVIDER_COMPLETED', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "contracts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "price" numeric(10,2) NOT NULL, "status" "public"."contracts_status_enum" NOT NULL DEFAULT 'ACTIVE', "completed_at" TIMESTAMP, "job_id" uuid NOT NULL, "accepted_offer_id" uuid NOT NULL, "client_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "assigned_worker_id" uuid, CONSTRAINT "REL_ca240c6a3243a193975ccc2718" UNIQUE ("job_id"), CONSTRAINT "REL_ffb37dfe5256dd015ab2c8c34e" UNIQUE ("accepted_offer_id"), CONSTRAINT "PK_2c7b8f3a7b1acdd49497d83d0fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" DROP COLUMN "unit_id"`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" DROP COLUMN "currency_id"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP COLUMN "estimated_duration_minutes"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP COLUMN "service_request_id"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "final_price"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "started_at"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "completed_at"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "before_service_photos"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "after_service_photos"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "provider_notes"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "REL_c113b7d5e19895123ebffb883d"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "service_request_id"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "REL_032c8d929b0d60944f52d444e0"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "accepted_offer_id"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "assigned_worker_id"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "customer_signature"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "photos"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "replied_at"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "is_verified"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "REL_6b129b5f4433000c7f97399bfe"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "job_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "provider_reply"`);
        await queryRunner.query(`ALTER TABLE "offers" ADD "estimated_duration" integer`);
        await queryRunner.query(`ALTER TABLE "offers" ADD "job_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "budget" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "is_urgent" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "contract_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "reviewer_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "reviewee_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" ADD "description" jsonb DEFAULT '{"en":"price details description","ar":"وصف الفئة"}'`);
        await queryRunner.query(`ALTER TYPE "public"."users_type_enum" RENAME TO "users_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_type_enum" AS ENUM('client', 'provider', 'worker')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "type" TYPE "public"."users_type_enum" USING "type"::"text"::"public"."users_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "type" SET DEFAULT 'provider'`);
        await queryRunner.query(`DROP TYPE "public"."users_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."offers_status_enum" RENAME TO "offers_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."offers_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN')`);
        await queryRunner.query(`ALTER TABLE "offers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "offers" ALTER COLUMN "status" TYPE "public"."offers_status_enum" USING "status"::"text"::"public"."offers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "offers" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."offers_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."jobs_status_enum" RENAME TO "jobs_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_status_enum" AS ENUM('OPEN', 'CONTRACTED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "status" TYPE "public"."jobs_status_enum" USING "status"::"text"::"public"."jobs_status_enum"`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "status" SET DEFAULT 'OPEN'`);
        await queryRunner.query(`DROP TYPE "public"."jobs_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "worker_profiles" ADD CONSTRAINT "FK_7c611bb4a08be1f32a858acc11e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "worker_profiles" ADD CONSTRAINT "FK_6414053d58ddae8fcac95999722" FOREIGN KEY ("employer_provider_id") REFERENCES "provider_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_b324119dcb71e877cee411f7929" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "worker_invitations" ADD CONSTRAINT "FK_b569547076cff49ab5e65252a6f" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offers" ADD CONSTRAINT "FK_4c17c75202c4bc562db9db43816" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_dec6205e2cd13841763710f9892" FOREIGN KEY ("client_id") REFERENCES "client_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD CONSTRAINT "FK_ca240c6a3243a193975ccc2718b" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD CONSTRAINT "FK_ffb37dfe5256dd015ab2c8c34e2" FOREIGN KEY ("accepted_offer_id") REFERENCES "offers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD CONSTRAINT "FK_9945462ca96b2c7d0a97e012cdc" FOREIGN KEY ("client_id") REFERENCES "client_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD CONSTRAINT "FK_d3d0ee245878be853d23a31b75c" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD CONSTRAINT "FK_28b60a5cf15e60dc10caaa277c6" FOREIGN KEY ("assigned_worker_id") REFERENCES "worker_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_d524fbe85d4619f66b10a664487" FOREIGN KEY ("contract_id") REFERENCES "contracts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_92e950a2513a79bb3fab273c92e" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a7b3e1afadd6b52f3b6864745e3" FOREIGN KEY ("reviewee_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a7b3e1afadd6b52f3b6864745e3"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_92e950a2513a79bb3fab273c92e"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_d524fbe85d4619f66b10a664487"`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "FK_28b60a5cf15e60dc10caaa277c6"`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "FK_d3d0ee245878be853d23a31b75c"`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "FK_9945462ca96b2c7d0a97e012cdc"`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "FK_ffb37dfe5256dd015ab2c8c34e2"`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "FK_ca240c6a3243a193975ccc2718b"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_dec6205e2cd13841763710f9892"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP CONSTRAINT "FK_4c17c75202c4bc562db9db43816"`);
        await queryRunner.query(`ALTER TABLE "worker_invitations" DROP CONSTRAINT "FK_b569547076cff49ab5e65252a6f"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_b324119dcb71e877cee411f7929"`);
        await queryRunner.query(`ALTER TABLE "worker_profiles" DROP CONSTRAINT "FK_6414053d58ddae8fcac95999722"`);
        await queryRunner.query(`ALTER TABLE "worker_profiles" DROP CONSTRAINT "FK_7c611bb4a08be1f32a858acc11e"`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_status_enum_old" AS ENUM('ASSIGNED', 'PROVIDER_ON_THE_WAY', 'PROVIDER_ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "status" TYPE "public"."jobs_status_enum_old" USING "status"::"text"::"public"."jobs_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "status" SET DEFAULT 'ASSIGNED'`);
        await queryRunner.query(`DROP TYPE "public"."jobs_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."jobs_status_enum_old" RENAME TO "jobs_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."offers_status_enum_old" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "offers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "offers" ALTER COLUMN "status" TYPE "public"."offers_status_enum_old" USING "status"::"text"::"public"."offers_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "offers" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."offers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."offers_status_enum_old" RENAME TO "offers_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."users_type_enum_old" AS ENUM('client', 'provider')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "type" TYPE "public"."users_type_enum_old" USING "type"::"text"::"public"."users_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "type" SET DEFAULT 'provider'`);
        await queryRunner.query(`DROP TYPE "public"."users_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_type_enum_old" RENAME TO "users_type_enum"`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "reviewee_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "reviewer_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "contract_id"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "is_urgent"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "budget"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP COLUMN "job_id"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP COLUMN "estimated_duration"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "provider_reply" text`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "provider_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "client_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "job_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "REL_6b129b5f4433000c7f97399bfe" UNIQUE ("job_id")`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "is_verified" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "replied_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "photos" jsonb`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "tags" jsonb`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "customer_signature" text`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "assigned_worker_id" uuid`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "accepted_offer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "REL_032c8d929b0d60944f52d444e0" UNIQUE ("accepted_offer_id")`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "provider_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "service_request_id" uuid`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "REL_c113b7d5e19895123ebffb883d" UNIQUE ("service_request_id")`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "provider_notes" jsonb`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "after_service_photos" jsonb`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "before_service_photos" jsonb`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "completed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "started_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "final_price" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "offers" ADD "service_request_id" uuid`);
        await queryRunner.query(`ALTER TABLE "offers" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "offers" ADD "estimated_duration_minutes" integer`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" ADD "currency_id" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" ADD "unit_id" uuid`);
        await queryRunner.query(`DROP TABLE "contracts"`);
        await queryRunner.query(`DROP TYPE "public"."contracts_status_enum"`);
        await queryRunner.query(`DROP TABLE "worker_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."worker_invitations_status_enum"`);
        await queryRunner.query(`DROP TABLE "worker_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."worker_profiles_status_enum"`);
        await queryRunner.query(`ALTER TABLE "offers" ADD CONSTRAINT "UQ_4c1ab15e915d32b19ff924459fb" UNIQUE ("provider_id", "service_request_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_blogs_status" ON "blogs" ("status") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_6b129b5f4433000c7f97399bfe9" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_d4e7e923e6bb78a8f0add754493" FOREIGN KEY ("client_id") REFERENCES "client_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_ba7ceb19946b8b23bf5939c930f" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_c113b7d5e19895123ebffb883df" FOREIGN KEY ("service_request_id") REFERENCES "client_service_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_dec6205e2cd13841763710f9892" FOREIGN KEY ("client_id") REFERENCES "client_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_d732a878487323978f118ab361c" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_032c8d929b0d60944f52d444e09" FOREIGN KEY ("accepted_offer_id") REFERENCES "offers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_ee11a5e8d47cd5e01747d52f3b3" FOREIGN KEY ("assigned_worker_id") REFERENCES "provider_workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offers" ADD CONSTRAINT "FK_d4e2f8e131609f51df1182ffc59" FOREIGN KEY ("service_request_id") REFERENCES "client_service_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_blogs_author" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" ADD CONSTRAINT "FK_cadeafa1e4d4a8e7263d7a0f7d0" FOREIGN KEY ("unit_id") REFERENCES "lookup_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_service_pricing" ADD CONSTRAINT "FK_c18c6384104a029f1b34121e0e2" FOREIGN KEY ("currency_id") REFERENCES "lookup_currencies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
