export enum AssetOwnerTypeEnum {
    PROVIDER_PROFILE = 'PROVIDER_PROFILE',
    CLIENT_PROFILE = 'CLIENT_PROFILE',
    BRANCH = 'BRANCH',
    PROVIDER_SERVICE = 'PROVIDER_SERVICE',
    PROVIDER_DOCUMENT = 'PROVIDER_DOCUMENT',
    BLOG = 'BLOG',
    REVIEW = 'REVIEW',
    JOB = 'JOB',
}
