export enum ProfileStatusStaticCode {
    DRAFT = 'DRAFT',
    PENDING_REVIEW = 'PENDING_REVIEW',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
}

export enum ProviderTypeStaticCode {
    INDIVIDUAL = 'INDIVIDUAL',
    COMPANY = 'COMPANY',
}

export enum BillingCycleStaticCode {
    MONTHLY = 'MONTHLY',
    THREE_MONTHS = 'THREE_MONTHS',
    SIX_MONTHS = 'SIX_MONTHS',
    YEARLY = 'YEARLY',
}

export enum CompanyTypeStaticCode {
    PRIVATE = 'PRIVATE',
    GOVERNMENT = 'GOVERNMENT',
    SEMI_GOVERNMENT = 'SEMI_GOVERNMENT',
}

export enum LanguageStaticCode {
    ENGLISH = 'ENGLISH',
    ARABIC = 'ARABIC',
    URDU = 'URDU',
    HINDI = 'HINDI',
    TAGALOG = 'TAGALOG',
    FRENCH = 'FRENCH',
    SPANISH = 'SPANISH',
    GERMAN = 'GERMAN',
    PORTUGUESE = 'PORTUGUESE',
    CHINESE = 'CHINESE',
    ITALIAN = 'ITALIAN',
    RUSSIAN = 'RUSSIAN',
    JAPANESE = 'JAPANESE',
    KOREAN = 'KOREAN',
    BENGALI = 'BENGALI',
    TURKISH = 'TURKISH',
    PERSIAN = 'PERSIAN',
    DUTCH = 'DUTCH',
    POLISH = 'POLISH',
    SWEDISH = 'SWEDISH',
    DANISH = 'DANISH',
    NORWEGIAN = 'NORWEGIAN',
    FINNISH = 'FINNISH',
    GREEK = 'GREEK',
    THAI = 'THAI',
    VIETNAMESE = 'VIETNAMESE',
    INDONESIAN = 'INDONESIAN',
    MALAY = 'MALAY',
    SWAHILI = 'SWAHILI',
    HEBREW = 'HEBREW',
    UKRAINIAN = 'UKRAINIAN',
    ROMANIAN = 'ROMANIAN',
    HUNGARIAN = 'HUNGARIAN',
    CZECH = 'CZECH',
    SLOVAK = 'SLOVAK',
    BULGARIAN = 'BULGARIAN',
    CROATIAN = 'CROATIAN',
    SERBIAN = 'SERBIAN',
    AMHARIC = 'AMHARIC',
    PASHTO = 'PASHTO',
    KURDISH = 'KURDISH',
    FILIPINO = 'FILIPINO',
}

// payment lookup table

export enum PaymentLookupCategory {
    SETTLEMENT_PREFERENCE = 'SETTLEMENT_PREFERENCE',
    POS_PROVIDER = 'POS_PROVIDER',
    CARD_TYPE = 'CARD_TYPE',
}

export enum SettlementPreferenceStaticCode {
    WEEKLY = 'WEEKLY',
    MONTHLY = 'MONTHLY',
}

export enum POSProviderStaticCode {
    PAYTAB = 'PAYTAB',
    STRIPE = 'STRIPE',
}

export enum CardTypeStaticCode {
    VISA = 'VISA',
    MASTERCARD = 'MASTERCARD',
    AMERICAN_EXPRESS = 'AMERICAN_EXPRESS',
    MADA = 'MADA',
}

export enum NationalityStaticCode {
    EMIRATI = 'emirati',
    INDIAN = 'indian',
    PAKISTANI = 'pakistani',
    BANGLADESHI = 'bangladeshi',
    FILIPINO = 'filipino',
    EGYPTIAN = 'egyptian',
    LEBANESE = 'lebanese',
    JORDANIAN = 'jordanian',
    SYRIAN = 'syrian',
    SUDANESE = 'sudanese',
    YEMENI = 'yemeni',
    IRAQI = 'iraqi',
    IRANIAN = 'iranian',
    SAUDI = 'saudi',
    NEPALESE = 'nepalese',
    SRI_LANKAN = 'sriLankan',
    CHINESE = 'chinese',
    BRITISH = 'british',
    AMERICAN = 'american',
    RUSSIAN = 'russian',
    TURKISH = 'turkish',
    AFGHAN = 'afghan',
    NIGERIAN = 'nigerian',
    ETHIOPIAN = 'ethiopian',
    INDONESIAN = 'indonesian',
    MOROCCAN = 'moroccan',
    FRENCH = 'french',
    GERMAN = 'german',
    THAI = 'thai',
    VIETNAMESE = 'vietnamese',
    KENYAN = 'kenyan',
    UGANDAN = 'ugandan',
}

export enum CityStaticCode {
    ABU_DHABI = 'abuDhabi',
    DUBAI = 'dubai',
    SHARJAH = 'sharjah',
    AL_AIN = 'alAin',
    AJMAN = 'ajman',
    RAS_AL_KHAIMAH = 'rasAlKhaimah',
    FUJAIRAH = 'fujairah',
    UMM_AL_QUWAIN = 'ummAlQuwain',
    KALBA = 'kalba',
    DIBBA_AL_FUJAIRAH = 'dibbaAlFujairah',
    MADINAT_ZAYED = 'madinatZayed',
    KHOR_FAKKAN = 'khorFakkan',
    AL_DHANNAH = 'alDhannah',
    GHAYATHI = 'ghayathi',
    DHAID = 'dhaid',
    JEBEL_ALI = 'jebelAli',
    LIWA_OASIS = 'liwaOasis',
    HATTA = 'hatta',
    AR_RAMS = 'arRams',
    DIBBA_AL_HISN = 'dibbaAlHisn',
    AL_JAZIRAH_AL_HAMRA = 'alJazirahAlHamra',
    MASAFI = 'masafi',
    MIRBAH = 'mirbah',
    MASFOUT = 'masfout',
    FALAJ_AL_MUALLA = 'falajAlMualla',
    AL_MADAM = 'alMadam',
    SWEIHAN = 'sweihan',
    SILA = 'sila',
    AL_MIRFA = 'alMirfa',
    DELMA = 'delma',
    GHANTOOT = 'ghantoot',
    AL_SHAMKHAH = 'alShamkhah',
    BANI_YAS = 'baniYas',
    MUSAFFAH = 'musaffah',
    MOHAMMED_BIN_ZAYED_CITY = 'mohammedBinZayedCity',
    KHALIFA_CITY = 'khalifaCity',
    SHAHAMA = 'shahama',
    RAHBA = 'rahba',
    DIGDAGA = 'digdaga',
    SHAWKAH = 'shawkah',
    KHATT = 'khatt',
    MANAMA = 'manama',
    JEBEL_DHANNA = 'jebelDhanna',
    DADNA = 'dadna',
    QIDFA = 'qidfa',
    AL_TAYYEBAH = 'alTayyebah',
    QURAYYAH = 'qurayyah',
    SIJI = 'siji',
    AL_BITHNAH = 'alBithnah',
    SHAAM = 'shaam',
    AL_HAMRIYAH = 'alHamriyah',
    MLEIHA = 'mleiha',
    AL_RAAS = 'alRaas',
    AL_SINNIYAH = 'alSinniyah',
    GHAYL = 'ghayl',
    AL_JEER = 'alJeer',
    AL_FAQA = 'alFaqa',
    AL_WAGAN = 'alWagan',
    AL_QUA = 'alQua',
    AL_MARFA = 'alMarfa',
    AL_RAFAAH = 'alRafaah',
    AL_AAMERAH = 'alAamerah',
    KHOR_KHUWAIR = 'khorKhuwair',
    ADHEN = 'adhen',
    HABSHAN = 'habshan',
    ASAB = 'asab',
    TARIF = 'tarif',
    AL_FAYAH = 'alFayah',
    AL_ARYAM = 'alAryam',
    AL_JURF = 'alJurf',
    AL_SAMHA = 'alSamha',
    AL_BAHYAH = 'alBahyah',
    AL_KHATIM = 'alKhatim',
    AL_TAWEELAH = 'alTaweelah',
}

export enum UnitStaticCode {
    METER = 'METER',
    HOUR = 'HOUR',
    DAY = 'DAY',
    PIECE = 'PIECE',
    KILOGRAM = 'KILOGRAM',
    KILOMETER = 'KILOMETER',
}

export enum CurrencyStaticCode {
    AED = 'AED',
    USD = 'USD',
    SAR = 'SAR',
    EUR = 'EUR',
}

