export enum NotificationType {
    NEW_JOB_REQUEST = 'NEW_JOB_REQUEST',
    PAYOUT_PROCESSED = 'PAYOUT_PROCESSED',
    DOCUMENT_EXPIRY = 'DOCUMENT_EXPIRY',
    JOB_STATUS_UPDATED = 'JOB_STATUS_UPDATED',
    SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
    NEW_OFFER = 'NEW_OFFER',
    PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
    ISSUE_RESOLVED = 'ISSUE_RESOLVED',
    SERVICE_REMINDER = 'SERVICE_REMINDER',
    CUSTOMER_MESSAGE = 'CUSTOMER_MESSAGE'
}
