export enum JobStatus {
    OPEN = 'OPEN',
    ASSIGNED = 'ASSIGNED',
    IN_PROGRESS = 'IN_PROGRESS',
    PROVIDER_COMPLETED = 'PROVIDER_COMPLETED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}
